- name: ping the server
  hosts: frontend # nothing but target server
  gather_facts: no
  tasks: 
  - name: ping the server
    ping: 
  - name: print the message
    debug:
    msg: "hello world from ansible"