- name: ping the server
  hosts: frontend # nothing but target server
  gather_facts: yes # to gather the information about the server
  tasks: 

  #now we will try to install install nginx on the server
  - name: install nginx
    dnf:
      name: nginx
      state: present
    become: yes # to run the command as root user
  - name: start nginx
    service:
      name: nginx
      state: started
    become: yes
  - name: print the message
    debug:
      msg: "nginx is installed and started successfully"
  - name: check nginx status
    service:
      name: nginx
      state: started
    register: nginx_status
    become: yes