- name: demo on command line variables
  hosts: frontend
  gather_facts: yes
  tasks:
  - name: print the message
    debug:
      msg: "Hello {{ name }}"

# sudo ansible-playbook -i inventory.ini -e "name=dharma" 08-vars.yaml