- name: pfreference of variables
  hosts: frontend
  gather_facts: yes
  vars:
    name: "ansible from play level"
  vars_files:
    - course.yaml
  vars_prompt:
  - name: "name"
    prompt: "Please enter your name"
  
  tasks:
  - name: print preference of variables
    vars:
      name: "ansible from task level variable"
    debug:
      msg: "The name is {{ name }}"

# first preference command line args
# second task
