- name: loop concept to test the loop concept
  hosts: frontend
  gather_facts: no

# loops are refer with a special variable called "item"
# we can use "with_items" to loop over a list of items
  tasks:
  - name: loop over a list of items
    debug:
      msg: "item is {{ item }}"
    loop:
    - dharma
    - akandam
    - devops