- name: loops 
  hosts: frontend
  gather_facts: no
  loop:
   - dharma
   - akandam
   - devops
# loops are refer with a special variable called "item"
# we can use "with_items" to loop over a list of items
  tasks:
  - name: loop over a list of items
    debug:
      msg: "item is {{ item }}"
    with_items: "{{ mylist }}"