# filters, we can convert string to list using split filter
# functions, listTOmap, mapTOlist
  hosts: frontend
  gather_facts: no
  vars:
    my_string:  dharma,akandam,devops
    
  tasks:
  - name: convert string to list using split filter
    debug:
      msg: "{{ my_string | split(',') }}"
  
  - name: convert list to map using listTOmap filter
   