# filters, we can convert string to list using split filter
# functions, listTOmap, mapTOlist
- name: filters
  hosts: frontend
  gather_facts: no
  vars:
    my_string:  dharma,akandam,devops
    tagMap:
      name: Ansible
      project: roboshop
      environment: dev
    Name: dharMa AKandam
    taglist:
      - name: Ansible
      - project: roboshop
      - environment: dev
    
  tasks:
  - name: convert string to list using split filter
    debug:
      msg: "{{ my_string | split(',') }}"
  
  - name: default variable
    debug:
      msg: "{{ akandam | default('devops') }}"

  - name: map to list
    debug:
      msg: "{{ tagMap | dict2items }}"

  - name: list to map
    debug:
      msg: "{{ tagMap | items2dict }}"

  - name: uppercase
    debug:
      msg: "{{ Name | upper }}"
  - name: lowercase
    debug:
      msg: "{{ Name | lower }}"
   