- name: demo on error handling
  hosts: local
  gather_facts: no
  tasks:
  - name: demo on errors
    command: id roboshop
    register: result
    ignore_errors: yes
  - name: print the result
    debug:
      var: result
  
  - name: create user
    command: useradd roboshop
    register: user
    when: result.rc != 0
  
  - name: print the user creation result
    debug:
      var: user