# ansible allows to run commands if modules are not available. This is not recommended but it is possible. We can use the raw module to run commands on remote hosts. The raw module does not require python to be installed on the remote host.
- name: filters
  hosts: local
  gather_facts: no
  tasks:
  - name: run a command
    #command: cat /ect/passwd | grep root #will get error because of we are trying shell command in command module
    shell: cat /etc/passwd | grep root

  - name: to store output of command in a variable
    shell: cat /etc/passwd | grep root
    register: output
  - name: print the output 
    debug:
      masg: "{{ output.stdout }}"