# ansible allows to run commands if modules are not available. This is not recommended but it is possible. We can use the raw module to run commands on remote hosts. The raw module does not require python to be installed on the remote host.
- name: commands
  hosts: frontend
  gather_facts: no
  tasks:
  - name: run a command
    command: cat /ect/passwd | grep root